### ISSUE TITLE
force-refresh fails to remove /tmp/zypperoni read only directories

### ISSUE THREAD

**Issue by pibesk** [pavinjosdev/zypperoni#1]
when i try to use force-refresh i receive long list of errors -
 rm:  canot remove directories and files in /tmp/zypperoni/....  "Read only filesystem"
 
 after that refresh command also fails with same error

**Comment by pavinjosdev** [comment]
Hi there, could you reboot and re-run the installation, I pushed some changes in the last 2 hours and made the v1 release just now:
https://github.com/pavinjosdev/zypperoni#installation

Then do:
```
sudo rm -rI /var/cache/zypp
sudo zypper refresh
```

Zypperoni takes some things for granted like having an existing `/var/cache/zypp` that's not corrupted. If you still have issues, please provide the output of `sudo zypperoni --debug force-refresh`

I've tested on OpenSuse TW, both latest snapshot and `20240116`.

**Comment by pibesk** [comment]
> Hi there, could you reboot and re-run the installation, I pushed some changes in the last 2 hours and made the v1 release just now: https://github.com/pavinjosdev/zypperoni#installation
> 
> Then do:
> 
> ```
> sudo rm -rI /var/cache/zypp
> sudo zypper refresh
> ```
> 
> Zypperoni takes some things for granted like having an existing `/var/cache/zypp` that's not corrupted. If you still have issues, please provide the output of `sudo zypperoni --debug force-refresh`
> 
> I've tested on OpenSuse TW, both latest snapshot and `20240116`.

After this & reboot, force-refresh still breaks 

While generating you logs in english i found out that with english:

export LOCALE=
export LOCALE-en_GB.utf8 

zypperoni force-refresh works ans later i can call zypperoni refresh and all looks ok

but with pl_PL.utf8 force-refresh breaks

added log file in english
[debug-en_GB.zip](https://github.com/pavinjosdev/zypperoni/files/14181979/debug-en_GB.zip)
 with force-refresh failing

**Comment by pibesk** [comment]
issue still exist
zypperoni refresh works for all languages
zypperoni force-refresh works only for english, when fails in pl_PL then its also broken with different locale until reboot

[debug-pl_PL.zip](https://github.com/pavinjosdev/zypperoni/files/14183202/debug-pl_PL.zip)
[debug-en_GB.zip](https://github.com/pavinjosdev/zypperoni/files/14183201/debug-en_GB.zip)

**Comment by pavinjosdev** [comment]
> issue still exist zypperoni refresh works for all languages zypperoni force-refresh works only for english, when fails in pl_PL then its also broken with different locale until reboot (zypperoni refresh is also broken after that too)
> 
> [debug-pl_PL.zip](https://github.com/pavinjosdev/zypperoni/files/14183202/debug-pl_PL.zip) [debug-en_GB.zip](https://github.com/pavinjosdev/zypperoni/files/14183201/debug-en_GB.zip)

Excellent debug reports, thank you!
Got why it's failing in Polish, I took a rather dubious shortcut to check for `umount`'s output in English, so it fails to properly unmount in any other language. Never occurred in my thick head the output of common shell tools could be in any other language.
Will push a fix soon! 😅

**Comment by pavinjosdev** [comment]
Fixed in zypperoni v0.1.1:
https://github.com/pavinjosdev/zypperoni/releases/tag/v0.1.1

Thank you for helping debug the issue 😀
